name: BSP${project.name}
main: ${project.groupId}.spawnsafe.SpawnSafe
version: ${project.version}
author: Mats391
commands:
   ssreload:
      description: Reloads SpawnSafe.
      permission: spawnsafe.reload
      usage: /<command>
permissions:
    spawnsafe.reload:
        description: Allows you to reload SpawnSafe
        default: op
